Repository AY2223S2-CS2103T-W11-3/tp, pull requests merged in 2023-03, with the labels that each got.

#25 Create Powercard Class
  src/main/java/seedu/address/model/powercard/Answer.java
  src/main/java/seedu/address/model/powercard/Powercard.java
  src/main/java/seedu/address/model/powercard/Question.java
Labels: type.Story, type.Task, priority.High

#37 Update README UI description
  README.md
Labels: type.Task, priority.High

#39 Create new Model class
  src/main/java/seedu/address/model/CardModel.java
  src/main/java/seedu/address/model/CardModelManager.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/powercard/UniqueCardList.java
  src/main/java/seedu/address/model/powerdeck/PowerDeck.java
  src/test/java/seedu/address/model/CardModelManagerTest.java
  src/test/java/seedu/address/model/powerdeck/PowerDeckTest.java
Labels: priority.High

#42 Add new methods to support multiple decks
  src/main/java/seedu/address/model/DeckModel.java
  src/main/java/seedu/address/model/DeckModelManager.java
  src/test/java/seedu/address/model/DeckModelManagerTest.java
Labels: priority.High

#51 Add SelectDeckCommand and various tweaks
  src/main/java/seedu/address/logic/commands/deckcommands/SelectDeckCommand.java
  src/main/java/seedu/address/model/DeckModel.java
  src/main/java/seedu/address/model/DeckModelManager.java
  src/main/java/seedu/address/model/powerdeck/PowerDeck.java
  src/main/java/seedu/address/model/util/SampleCardUtil.java
Labels: priority.Medium

#58 Refactor Card - Email & Phone
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/card/Card.java
  src/main/java/seedu/address/model/card/Email.java
  src/main/java/seedu/address/model/card/Phone.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCardDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/card/CardTest.java
  src/test/java/seedu/address/model/card/EmailTest.java
  src/test/java/seedu/address/model/card/PhoneTest.java
  src/test/java/seedu/address/model/card/QuestionContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCardTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium

#64 Remove Phone and Email fields in GUI
  src/main/java/seedu/address/model/util/SampleCardUtil.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
Labels: priority.Low

#66 Refactor code to allow Card class to accept additional attribute Deck
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/card/Card.java
  src/main/java/seedu/address/model/deck/Deck.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCardTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#67 Add select deck feature
  src/main/java/seedu/address/logic/commands/deckcommands/SelectDeckCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SelectDeckCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/deck/Deck.java
  src/main/java/seedu/address/model/deck/UniqueDeckList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#89 Modify Optional usage
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/FlipCommand.java
  src/main/java/seedu/address/logic/parser/MasterDeckParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/review/Review.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.Medium

#97 Enable Storage to load the decks from JSON file
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: priority.High

#136 Refactor Card class constructor to take in Deck instead of Optional<Deck>
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/card/Card.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedCard.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/testutil/CardBuilder.java
Labels: priority.High

#137 Allow non-alphanumeric inputs for question
  src/main/java/seedu/address/model/card/Question.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/card/AnswerTest.java
  src/test/java/seedu/address/model/card/QuestionTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCardTest.java
Labels: priority.High

#141 Delete unnecessary UpdateFilteredLists in addDeck and deleteDeck
  src/main/java/seedu/address/logic/commands/DeleteDeckCommand.java
  src/main/java/seedu/address/logic/commands/EditDeckCommand.java
  src/main/java/seedu/address/model/MasterDeck.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/card/Card.java
  src/main/java/seedu/address/model/deck/UniqueDeckList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddDeckCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteDeckCommandTest.java
  src/test/java/seedu/address/model/card/CardTest.java
Labels: priority.Medium

#149 Revamp EditDeckCommand to fix bugs
  src/main/java/seedu/address/logic/commands/EditDeckCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditDeckCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/MasterDeck.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/deck/Deck.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddDeckCommandTest.java
  src/test/java/seedu/address/logic/commands/EditDeckCommandTest.java
Labels: priority.High

#173 Disallow Card from existing without a Deck
  src/main/java/seedu/address/logic/commands/cardcommands/AddCommand.java
  src/main/java/seedu/address/logic/commands/cardcommands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/MasterDeck.java
  src/main/java/seedu/address/model/card/Card.java
  src/main/java/seedu/address/model/card/CardInDeckPredicate.java
  src/main/java/seedu/address/model/card/UniqueCardList.java
  src/main/java/seedu/address/storage/JsonAdaptedCard.java
  src/main/java/seedu/address/storage/JsonSerializableMasterDeck.java
  src/test/data/JsonSerializableMasterDeckTest/duplicateCardMasterDeck.json
  src/test/java/seedu/address/logic/commands/cardcommands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/cardcommands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/cardcommands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/cardcommands/EditCardDescriptorTest.java
  src/test/java/seedu/address/logic/commands/cardcommands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/deckcommands/AddDeckCommandTest.java
  src/test/java/seedu/address/logic/commands/deckcommands/DeleteDeckCommandTest.java
  src/test/java/seedu/address/logic/commands/deckcommands/EditDeckCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/MasterDeckTest.java
  src/test/java/seedu/address/model/card/CardTest.java
  src/test/java/seedu/address/model/card/UniqueDeckListTest.java
  src/test/java/seedu/address/testutil/AddCardDescriptorBuilder.java
  src/test/java/seedu/address/testutil/CardBuilder.java
  src/test/java/seedu/address/testutil/EditCardDescriptorBuilder.java
Labels: priority.High

#175 Update ReviewCard.fxml to centralise Answer field in GUI under Review
  src/main/resources/view/ReviewCard.fxml
Labels: severity.Low

#185 Create visual distinction when select a deck
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/deckcommands/UnselectDeckCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/deck/Deck.java
  src/main/java/seedu/address/ui/DeckCard.java
  src/main/java/seedu/address/ui/DeckListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/UnselectDeckCommandTest.java
Labels: priority.Medium

#187 Update UI to follow mock up more closely
  src/main/java/seedu/address/ui/DeckListPanel.java
  src/main/java/seedu/address/ui/DeckNamePanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/ReviewStatsPanel.java
  src/main/resources/view/DeckName.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/ReviewStat.fxml
  src/main/resources/view/Theme.css
  src/main/resources/view/UnflippedReviewCard.fxml
Labels: priority.Medium

#194 Fix bug that answer is revealed in Review mode
  src/main/java/seedu/address/ui/ReviewCard.java
Labels: severity.High

#204 [GUI] Main Mode will not show any cards, until a deck is selected.
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/cardcommands/AddCommand.java
  src/main/java/seedu/address/logic/commands/deckcommands/UnselectDeckCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/DeckName.java
  src/main/java/seedu/address/ui/DeckNamePanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/cardcommands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/cardcommands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/cardcommands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/deckcommands/AddDeckCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.Medium

#196 Add activity diagrams to DG under Implementation
  docs/DeveloperGuide.md
  docs/diagrams/CommandActivityFlowDiagram.puml
  docs/diagrams/CommandValidityActivityDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/CommandActivityFlowDiagram.png
  docs/images/CommandValidityActivityDiagram.png
  docs/images/ModelClassDiagram.png
Labels: priority.High

#222 Update IsSameCardPredicate
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/card/IsSameCardPredicate.java
Labels: priority.Medium

#233 Complete refactor of Review class
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/reviewcommands/SetReviewLimitCommand.java
  src/main/java/seedu/address/logic/parser/MasterDeckParser.java
  src/main/java/seedu/address/logic/parser/SetReviewLimitCommandParser.java
  src/main/java/seedu/address/model/MasterDeck.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/card/Card.java
  src/main/java/seedu/address/model/card/UniqueCardList.java
  src/main/java/seedu/address/model/review/Review.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/commands/cardcommands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/deckcommands/AddDeckCommandTest.java
  src/test/java/seedu/address/model/ModelStub.java
  src/test/java/seedu/address/model/card/CardTest.java
  src/test/java/seedu/address/testutil/CardBuilder.java
Labels: priority.High

#244 Update UG for Deck commands
  docs/UserGuide.md
Labels: priority.High

#247 Fix filter text bug
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High

#248 Add powercards logo
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/powercardslogo.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: priority.High
